### ISSUE TITLE
Extending Physx API Bindings - exploration of options.

### ISSUE THREAD

**Issue by diarmidmackenzie** [c-frame/physx#15]
I've been looking at extending the available PhysX API bindings.

My immediate goal was to experiment with [Projection](https://gameworksdocs.nvidia.com/PhysX/4.1/documentation/physxguide/Manual/Joints.html#projection) on Fixed Joints to solve a problem where walls of bricks joined together with fixed joints become wobbly above a certain size.

For future reference, this issue documents my progress on a couple of fronts.

1. Rebuilding the existing WASM build, using the approach described [here](https://github.com/ashconnell/physx-js).

This is the "obvious" approach, and should have been straightforward.

I made some minor updates to enable a couple of new API calls [here](https://github.com/zach-capalbo/PhysX/compare/emscripten_wip...diarmidmackenzie:PhysX-1:joint-projection)

Rebuilding should be pretty straightforward, but I had a few issues
- running natively on Windows, the npm scripts hit errors
- so I ran WSL so that I had a linux environment on my Windows PC
- I was able to set that up with Docker following [these instructions](https://docs.docker.com/desktop/windows/wsl/#enabling-docker-support-in-wsl-2-distros) and to set up node on WSL using [these instructions](https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl)
- Having cloned repos within Windows, I found I had some problems with file format (CRLF vs LF).  Simplest solution was to delete the repos I had cloned in Windows, and re-clone from the WSL command line.
- That was enough to get things going, but I hit a couple of compiler warnings, which stopped the build from working, as described [here](https://github.com/ashconnell/physx-js/issues/16).
- Potentially I could work around those issues by either changing the compiler flags so it's more tolerant of warnings, or fixing up the cpp code.  But it seemed odd that I should have to do either of these.  At this point I paused & looked at a 2nd option.

2. Migrating to [physx-js-webidl](https://github.com/fabmax/physx-js-webidl)

This is used by [PHY](https://github.com/lo-th/phy), a Physics library for Three.js that I've been looking at.

Benefits of using this WASM build include:
- it's already updated tp use PhysX 5.1
- it seems to aleady expose more of the API (e.g. projection tolerance settings above).

I've been making some changes on [this branch](https://github.com/diarmidmackenzie/physx/tree/fixed-joints-5.1) to try to get this working.  Unfortunately it's not staightforward.

The way the PhysX CPP API gets translated into a JS API is quite different for this alternative build.

Working through the differences has basically been a matter of:
- running examples to see what errors are hit
- comparing bindings defined for the perviosu version of PhysX [here](https://github.com/zach-capalbo/PhysX/blob/emscripten_wip/physx/source/physxwebbindings/src/PxWebBindings.cpp) with the web IDL bindings [here](https://github.com/fabmax/PhysX/blob/webidl-bindings/physx/source/webidlbindings/src/common/WebIdlBindings.h)
- making updates & testing again.

If made a bunch of fixes & hit a number of errors, but still hitting problems inside the physics simulation:

```
physx-js-webidl.wasm:0x11b817 Uncaught RuntimeError: null function or function signature mismatch
    at physx-js-webidl.wasm:0x11b817
    at physx-js-webidl.wasm:0x11bc19
    at physx-js-webidl.wasm:0x9ff13
    at eval (physx-js-webidl.js:969:22)
    at PxScene.simulate.PxScene.simulate (physx-js-webidl.js:30889:50)
    at i.tock (physics.js:746:16)
    at bind.js:12:17
    at i.tock (index.js:127:7)
    at v.tock (a-scene.js:724:36)
    at e.object3D.onAfterRender (a-scene.js:52:34)
```    
Presumably something has been initialized incorrectly due to the change in API, but it's not straightforward to find out what.

I'm wrapping up this investigation for now.  While I had wanted to experiment with projection of Fixed Joints, I only thought there was a small chance of it solving my problems, and think a better solution is likely to be by following the advice in the API docs and use a single actor with multiple shapes...

> Note All joints are enforced by the dynamics solver, so although under ideal conditions the objects will maintain their spatial relationship, there may be some drift. A common alternative, which is cheaper to simulate and does not suffer from drift, is to construct a single actor with multiple shapes. However fixed joints are useful, for example, when a joint must be breakable or report its constraint force.

Nevertheless, it's likely that we'll want to extend the exposed parts of the PhysX API and/or move to 5.1+ at some point, so with that in mind, I've documented my investigations so far here.

**Comment by kfarr** [comment]
Wow thanks for this writeup and sharing this repo! https://github.com/fabmax/physx-js-webidl
* I notice webidl bindings include vehicles :)
* For the error `at eval (physx-js-webidl.js:969:22)` I notice that js file is minimized, is it possible to see the context of the error in a non-minified version?
* Another approach could be to step through the logic in this js example: https://github.com/fabmax/physx-js-webidl/blob/main/dist/helloworld.html and see if there are any obvious steps missing?

**Comment by enzofrancescaHM** [comment]
Sorry to write on this thread 1 year after last communications, but it would be nice to have Physx migrated to physx-js-webidl because it have support for vehicles and this is a big point, useful for a-frame + physx.
So, just a manifestation of interest!

**Comment by vincentfretin** [comment]
I got it to build with the trzeci/emscripten:1.39.5-upstream docker image, without your commit 
```
git clone git@github.com:ashconnell/physx-js.git
cd physx-js
#git clone -b emscripten_wip git@github.com:prestomation/PhysX.git
git clone -b emscripten_wip git@github.com:zach-capalbo/PhysX.git
cd PhysX
git remote add nvidia git@github.com:NVIDIAGameWorks/PhysX.git
git fetch nvidia
git rebase nvidia/4.1
# fix the conflict in physx/source/geomutils/src/gjk/GuGJKType.h search for HEAD and keep the 2nd line
git add physx/source/geomutils/src/gjk/GuGJKType.h
git rebase --continue
git remote add diarmidmackenzie git@github.com:diarmidmackenzie/PhysX-1.git
git fetch diarmidmackenzie
#git cherry-pick 95391dccde94bc11829c615da76d9c6a63346295 # https://github.com/zach-capalbo/PhysX/compare/emscripten_wip...diarmidmackenzie:PhysX-1:joint-projection
cd ..
sed -i -e 's|trzeci/emscripten |trzeci/emscripten:1.39.5-upstream |' package.json
npm run generate
mkdir dist
npm run make
```

With your commit I got an error:
```
[100%] Building CXX object sdk_source_bin/CMakeFiles/PhysXWebBindings.dir/src/PhysX/physx/source/physxwebbindings/src/PxWebBindings.cpp.o
/src/PhysX/physx/source/physxwebbindings/src/PxWebBindings.cpp:344:59: error: no member named 'setProjectionLinearTolerance' in 'physx::PxJoint'
      .function("setProjectionLinearTolerance", &PxJoint::setProjectionLinearTolerance)
                                                 ~~~~~~~~~^
/src/PhysX/physx/source/physxwebbindings/src/PxWebBindings.cpp:345:60: error: no member named 'setProjectionAngularTolerance' in 'physx::PxJoint'
      .function("setProjectionAngularTolerance", &PxJoint::setProjectionAngularTolerance)
                                                  ~~~~~~~~~^
2 errors generated.
```

**Comment by vincentfretin** [comment]
Comparing the current and new physx.release.js, it seems that the current physx.release.js we have was build with a later version than emscripten:1.39.5, it's using the newer INITIAL_MEMORY instead of the deprecated TOTAL_MEMORY
So that was a version between 1.39.5 and 1.39.18 https://hub.docker.com/r/trzeci/emscripten/tags

![Image](https://github.com/user-attachments/assets/381547a5-a46c-4776-87c2-f5b3ed4adb5f)

**Comment by vincentfretin** [comment]
I'm still testing some versions. I tested also with the official docker image `-e EMSCRIPTEN=/emsdk/upstream/emscripten 
 emscripten/emsdk:3.1.52`
The latest version of emscripten / clang is more strict with the cpp code, instead of fixing the cpp code, I ended up adding a bunch of flags
`-Wno-dtor-name -Wno-suggest-override -Wno-suggest-destructor-override -Wno-tautological-value-range-compare -Wno-deprecated-copy-dtor -Wno-deprecated-copy -Wno-unsafe-buffer-usage -Wno-unsafe-buffer-usage-in-libc-call -Wno-reserved-identifier -Wno-missing-include-dirs -Wno-invalid-offsetof -Wno-bitwise-instead-of-logical -Wno-switch-default -Wno-unused-but-set-variable -Wno-unaligned-access`
to `physx/source/compiler/cmake/emscripten/CMakeLists.txt`
The PhysX code compiles but the final emscripten step for the binding fails.

I'm trying old emscripten versions with the deprecated trzeci/emscripten image and first trying to reproduce the build we currently have. To reproduce the memory maximum, I had to set `-s MAXIMUM_MEMORY=2GB` in `physx/source/compiler/cmake/emscripten/PhysXWebBindings.cmake`
full line:
`SET(EMSCRIPTEN_BASE_OPTIONS "--bind -s MODULARIZE=1 -s EXPORT_NAME=PHYSX -s ALLOW_MEMORY_GROWTH=1 -s MAXIMUM_MEMORY=2GB")`
but still getting `Uncaught (in promise) RuntimeError: null function or function signature mismatch` error when the wasm is loaded so I'm thinking there is an issue in the binding code, and I'm not sure from what commit the current build we have came from.

**Comment by vincentfretin** [comment]
Zachary definitely used at least trzeci/emscripten:1.39.17-upstream because we have that change
https://github.com/emscripten-core/emscripten/commit/6f98f6aa2571f5a72ab04e67d7606f86e6a141fb
in the current build that was introduced in 1.39.17. The latest from deprecated image is 1.39.18-upstream and has the same output for the js file.
But even that version we have the `PX_UNUSED(hitsSpaceLeft)` error.
I think he just added the flags to silence the errors or just simply removed `-Wall` from the list that treats warnings as errors.
But unfortunately I still get "RuntimeError: null function or function signature mismatch" even with original branch https://github.com/zach-capalbo/PhysX/commits/emscripten_wip/ without rebasing from nvidia 4.1 branch.

**Comment by vincentfretin** [comment]
Oh! With https://github.com/zach-capalbo/PhysX/commits/emscripten_wip/ without the last commit TriMesh bindings, it works!

**Comment by vincentfretin** [comment]
Rebasing from nvidia 4.1 branch also produces "Uncaught (in promise) RuntimeError: null function or function signature mismatch" so I gave up on that rebase. 

I forked the two repos in c-frame
https://github.com/c-frame/physx-js
https://github.com/c-frame/PhysXSDK
and made those changes to have a reproducible build
https://github.com/c-frame/PhysXSDK/commits?author=vincentfretin&since=2025-01-23&until=2025-02-23
https://github.com/c-frame/physx-js/commits?author=vincentfretin&since=2025-01-23&until=2025-02-23
You can try again your changes @diarmidmackenzie if you want.

**Comment by vincentfretin** [comment]
Okay so the latest commit from Zach about TriMesh bindings is actually working. I force pushed the branch to revert my revert. I merged the nvidia 4.1 branch so we get the 4.1.2 changes https://nvidiagameworks.github.io/PhysX/4.1/release_notes.html and I exposed joint limit and projection tolerances in https://github.com/c-frame/PhysXSDK/commit/0f6fa8b7f4b0f4d043d358b5b200da63a714ff70
I will try now to use the limit for the revolute and prismatic joints, that's what I'm interested in.

**Comment by vincentfretin** [comment]
FYI setProjectionLinearTolerance/setProjectionAngularTolerance are not on the base class PxJoint, but on each joint that supports it. That's why your commit didn't compile.

![Image](https://github.com/user-attachments/assets/48e11bed-bb80-44d6-9c89-99e1e41eb202)

**Comment by enzofrancescaHM** [comment]
Impressive, @vincentfretin. As I stated in my previous message my interest is on exposing vehicle bindings for using in A-Frame. If I can help in some way, here I am.

**Comment by vincentfretin** [comment]
@enzofrancescaHM feel free to experiment exposing the bindings for that now that we have a working process to build the wasm file. Note that the vehicle api changed completely in PhysX 5.x so it may not be worth it to spend time on that with the current 4.1.2 version we use. See https://nvidia-omniverse.github.io/PhysX/physx/5.5.1/docs/MigrationTo51.html#vehicles
My current scope is to make the revolute and prismatic constraints work for a customer project.
For vehicles I think we should try to use the physx-js-webidl bindings like @diarmidmackenzie explored.

For ammo, I did https://github.com/c-frame/aframe-racing-game to test vehicles controls if you didn't see it.

**Comment by enzofrancescaHM** [comment]
> [@enzofrancescaHM](https://github.com/enzofrancescaHM) feel free to experiment exposing the bindings for that now that we have a working process to build the wasm file. Note that the vehicle api changed completely in PhysX 5.x so it may not be worth it to spend time on that with the current 4.1.2 version we use. See https://nvidia-omniverse.github.io/PhysX/physx/5.5.1/docs/MigrationTo51.html#vehicles My current scope is to make the revolute and prismatic constraints work for a customer project. For vehicles I think we should try to use the physx-js-webidl bindings like [@diarmidmackenzie](https://github.com/diarmidmackenzie) explored.
> 
> For ammo, I did https://github.com/c-frame/aframe-racing-game to test vehicles controls if you didn't see it.

yeah, I played with ammo extensively in the past, you can watch a little experiment here: https://www.youtube.com/watch?v=W6zhs0Gzy1U

**Comment by vincentfretin** [comment]
> If you're testing locally a build, be sure to put back in `src/physics.js` `wasmUrl: {default: "/wasm/physx.release.wasm"},` instead of `wasmUrl: {default: "https://cdn.jsdelivr.net/gh/c-frame/physx/wasm/physx.release.wasm"},` and run `npm run dist`
> 
> I was testing with the wasm file from the cdn this whole time. No wonder that I got the "Uncaught (in promise) RuntimeError: null function or function signature mismatch" error. TT

If fixed this in #26 you just need to run `npm run dev` now.
